apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-inspector-out
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: k8s-inspector-nfs-pv
